version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./temp_uploads:/app/temp_uploads
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - cognisgraph-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./temp_uploads:/app/temp_uploads
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - cognisgraph-network

networks:
  cognisgraph-network:
    driver: bridge 