apiVersion: v2
name: cognisgraph
description: A Helm chart for deploying CognisGraph knowledge graph system
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/bharti26/cognisgraph/main/helm/cognisgraph/icon.svg
maintainers:
  - name: CognisGraph Team
    email: bhartigoel0812@gmail.com
keywords:
  - knowledge-graph
  - ai
  - nlp
  - streamlit
  - fastapi
home: https://github.com/bharti26/cognisgraph
sources:
  - https://github.com/bharti26/cognisgraph
dependencies:
  - name: ingress-nginx
    version: "4.8.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
  - name: cert-manager
    version: "1.13.0"
    repository: "https://charts.jetstack.io"
    condition: ingress.tls.enabled 