global:
  environment: production

config:
  logLevel: "INFO"
  debug: "false"
  cacheDir: "/tmp/cognisgraph/cache"
  modelPath: "/app/models"
  api:
    host: "0.0.0.0"
    port: "8000"
    workers: "4"
    timeout: "60"
  ui:
    port: "8501"
    address: "0.0.0.0"
    headless: "true"
    enableCors: "false"
    enableXsrfProtection: "true"
    maxUploadSize: "200"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: cognisgraph.example.com
      paths:
        - path: /api
          pathType: Prefix
          service: api
          port: 8000
        - path: /
          pathType: Prefix
          service: ui
          port: 8501
  tls:
    - secretName: cognisgraph-tls
      hosts:
        - cognisgraph.example.com

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"

resources:
  api:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  ui:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

serviceAccount:
  create: true
  annotations: {}

# ... existing code ... 