apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognisgraph.fullname" . }}-api
  labels:
    {{- include "cognisgraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cognisgraph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognisgraph.fullname" . }}-ui
  labels:
    {{- include "cognisgraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cognisgraph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui 